Add an option to add @here mentions to Slack messages on failures
nsbno/terraform-stepfunction-status-slack pull request #15
Opened 2023-05-12 09:51 UTC by jholtan

2023-05-12 09:53 UTC, petterdaae approved these changes

2023-05-15 07:10 UTC, nicolaei requested changes
Liker tanken! Bare noen småting her.

2023-05-15 07:10 UTC, nicolaei commented on variables.tf
> +variable "attention_on_failure" {
Jeg ville kalt denne `tag channel on failure`

2023-05-15 07:10 UTC, nicolaei commented on src/pipeline-status-slack.py
> +    attention = os.environ["ATTENTION"]
Her må du JSON loade, ellers får du alltid true!
```suggestion
    attention = json.loads(os.environ["ATTENTION"])
```

Husk å sjekke at `json` er importert.

2023-05-15 12:40 UTC, jholtan commented on variables.tf
> +variable "attention_on_failure" {
Enig!

2023-05-15 12:41 UTC, jholtan commented on src/pipeline-status-slack.py
> +    attention = os.environ["ATTENTION"]
Fiksa det på samme måten som den andre boolske miljøvariabelen.

2023-06-26 05:25 UTC, merged